coverage:
  status:
    project:
      default:
        target: 90%
    patch:
      default:
        target: 90%

flags:
  craftty-ink:
    paths:
      - crates/craftty-ink/
  craftty:
    paths:
      - crates/craftty/
